defmodule DaySevenTest do
  use ExUnit.Case

  setup_all do
    file_content = """
    .......S.......
    ...............
    .......^.......
    ...............
    ......^.^......
    ...............
    .....^.^.^.....
    ...............
    ....^.^...^....
    ...............
    ...^.^...^.^...
    ...............
    ..^...^.....^..
    ...............
    .^.^.^.^.^...^.
    ...............
    """

    File.write!("testfile.txt", file_content)
    on_exit(fn -> File.rm!("testfile.txt") end)
  end

  test "part one test" do
    assert DaySeven.part_one("testfile.txt") == 21
  end
  test "part one solution" do
    assert DaySeven.part_one("../../AoC-2025-inputs/input7.txt") == :solution1
  end

  test "part two test" do
    assert DaySeven.part_two("testfile.txt") == 40
  end
  test "part two solution" do
    assert DaySeven.part_two("../../AoC-2025-inputs/input7.txt") == :solution2
  end
end
